# =============================================================================
# Freeze every rule's verdicts over a deterministic input grid
# =============================================================================
#
# Pattern from moj-analytical-services/splink (MIT), tests/test_compare_splink2.py:
# outputs of the previous implementation are frozen as CSVs the current one
# must reproduce. A deterministic package can demand it bit-for-bit. The test
# (test-verdict-snapshot.R) recomputes the grid and requires identity; a diff
# here is a BEHAVIOUR CHANGE, to be made deliberately: rerun this script,
# review the verdict diff row by row like code, and say so in NEWS.
#
# Rerun from the package root:  Rscript data-raw/verdict_snapshot.R

suppressMessages(pkgload::load_all(".", quiet = TRUE))

# -- deterministic input pools (no randomness: the grid IS the spec) ----------
load("data/NICKNAME_EDGES.rda")
formals_pool <- head(sort(unique(NICKNAME_EDGES$name)), 25)
nicks_pool   <- head(sort(unique(NICKNAME_EDGES$nickname)), 25)
name_pool <- unique(c(formals_pool, nicks_pool,
                      "ELISABETH", "K.C.", "MARY JANE", "VL", "B", "",
                      NA_character_))

gender_pool  <- c("M", "F", "Male", "female", "U", "X", "1", "2", "", NA)
suffix_pool  <- c("JR", "Jr.", "JUNIOR", "SR", "SNR", "II", "2ND", "III",
                  "3RD", "IV", "V", "MD", "", NA)
license_nums <- c("12345", "MD-12345", "MD12345", "0052", "52", "A.1.2", "",
                  NA)
license_sts  <- c("CO", "TX", "", NA)

grid_of <- function(pool) expand.grid(a = pool, b = pool,
                                      stringsAsFactors = FALSE,
                                      KEEP.OUT.ATTRS = FALSE)

rows <- list()
g <- grid_of(name_pool)
rows$middle <- data.frame(
  rule = "middle", a = g$a, state_a = "", b = g$b, state_b = "",
  verdict = middle_agreement(middle_tokens(g$a), middle_tokens(g$b)),
  stringsAsFactors = FALSE)
rows$nickname <- data.frame(
  rule = "nickname", a = g$a, state_a = "", b = g$b, state_b = "",
  verdict = nickname_agreement(g$a, g$b), stringsAsFactors = FALSE)

g <- grid_of(gender_pool)
rows$gender <- data.frame(
  rule = "gender", a = g$a, state_a = "", b = g$b, state_b = "",
  verdict = gender_agreement(g$a, g$b), stringsAsFactors = FALSE)

g <- grid_of(suffix_pool)
rows$suffix <- data.frame(
  rule = "suffix", a = g$a, state_a = "", b = g$b, state_b = "",
  verdict = suffix_agreement(g$a, g$b), stringsAsFactors = FALSE)

g <- expand.grid(a = license_nums, state_a = license_sts,
                 b = license_nums, state_b = license_sts,
                 stringsAsFactors = FALSE, KEEP.OUT.ATTRS = FALSE)
rows$license <- data.frame(
  rule = "license", a = g$a, state_a = g$state_a, b = g$b, state_b = g$state_b,
  verdict = license_agreement(g$a, g$state_a, g$b, g$state_b),
  stringsAsFactors = FALSE)

snap <- do.call(rbind, rows)
snap[is.na(snap)] <- "<NA>"                     # NA is an input value here
rownames(snap) <- NULL

out <- "tests/testthat/fixtures/golden/snapshot.csv"
header <- c(
  "## Frozen verdict snapshot over a deterministic input grid.",
  "## Pattern from moj-analytical-services/splink (MIT), test_compare_splink2.py.",
  "## Regenerate ONLY deliberately: Rscript data-raw/verdict_snapshot.R, then",
  "## review the verdict diff row by row and record the change in NEWS.",
  "## Provenance: generated by data-raw/verdict_snapshot.R from the package's",
  "## own rules; input pools are fixed constants plus the first 25 names and",
  "## nicknames of NICKNAME_EDGES. '<NA>' encodes a genuine NA input.")
writeLines(c(header, "rule,a,state_a,b,state_b,verdict"), out)
write.table(snap, out, sep = ",", row.names = FALSE, col.names = FALSE,
            append = TRUE, qmethod = "double")
cat(nrow(snap), "verdicts frozen to", out, "\n")
